version: '3.8'

services:
  db:
    image: postgres:13
    container_name: shorturl_db
    environment:
      POSTGRES_DB: short-url
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shorturl_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/short-url
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8081:8081"
    depends_on:
      - db

volumes:
  db_data:
