version: '3.7'
services:
  elasticsearch:
    image: elastic/elasticsearch:8.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - elk

  logstash:
    image: logstash:8.10.1
    container_name: logstash
    volumes:
      - app_logs:/logs
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./certs:/usr/share/logstash/config/certs
    ports:
      - "5044:5044"
    networks:
      - elk

  kibana:
    image: kibana:8.10.1
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  app:
    build: .
    container_name: spring-app
    volumes:
      - app_logs:/logs
    ports:
      - "8081:8081"
    networks:
      - elk
    depends_on:
      - logstash

  filebeat:
    image: elastic/filebeat:8.10.0
    container_name: filebeat
    volumes:
      - app_logs:/logs
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    networks:
      - elk
    depends_on:
      - elasticsearch
      - logstash

networks:
  elk:
    driver: bridge

volumes:
  app_logs:
