
input {
  file {
    path => "/logs/app.log"
    start_position => "beginning"
  }
}

output {
  # stdout { codec => rubydebug }
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    user => "${ELASTIC_USERNAME}"
    password => "${ELASTIC_PASSWORD}"
    ssl => true
    # cacert => "/usr/share/logstash/config/certs/http_ca.crt"
    ssl_verification_mode => "none"
    index => "logs"
  }
}
