
input {
  file {
    path => "/logs/app.log"
    start_position => "beginning"
  }
}

output {
  # stdout { codec => rubydebug }
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    user => "elastic"
    password => "PA4dys7HU0Nm=ByI6E9U"
    ssl_enabled => true
    cacert => "/usr/share/logstash/config/certs/http_ca.crt"
    index => "logs"
  }
}
