spring:
  application:
    name: short-url
  datasource:
    url: jdbc:postgresql://localhost:5432/short-url
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:/db/migration

server:
  port: 8081

shorturl:
  cleanup:
    interval: 1800000 # 30 минут в миллисекундах