keycloak.auth-server-url=https://keycloak.effective-mobile.ru/
keycloak.realm=effective-mobile
keycloak.resource=spring-boot-client

server.port=8081
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${keycloak.auth-server-url}realms/${keycloak.realm}/protocol/openid-connect/certs

spring.security.oauth2.client.registration.keycloak.client-id=spring-boot-client
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri=http://localhost:8081/login/oauth2/code/keycloak
spring.security.oauth2.client.registration.keycloak.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.keycloak.client-secret=${keycloak.admin.client-secret} # Use the same secret for OAuth2 client login
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email,groups
spring.security.oauth2.client.provider.keycloak.issuer-uri=${keycloak.auth-server-url}realms/${keycloak.realm}
spring.security.oauth2.client.provider.keycloak.user-info-uri=${keycloak.auth-server-url}realms/${keycloak.realm}/protocol/openid-connect/userinfo

# Keycloak Admin Client Configuration
keycloak.admin.server-url=${keycloak.auth-server-url}
keycloak.admin.realm=${keycloak.realm}
keycloak.admin.client-id=spring-boot-client # Explicitly set client-id for admin client as well
keycloak.admin.client-secret=YXdGEGzL7ax7WYfytTxJ3JkYHsaKnTad # IMPORTANT: Replace with actual client secret if using Service Account
# keycloak.admin.username=admin # Uncomment and set if using an admin user directly
# keycloak.admin.password=password # Uncomment and set if using an admin user directly

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.client=DEBUG