spring:
  datasource:
    url: jdbc:tc:postgresql:15-alpine:///testdb
    username: test
    password: test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  data:
    redis:
      testcontainers:
        image: redis:7.2-alpine

  liquibase:
    enabled: true

  test:
    containers:
      enabled: true